server {
    listen 80;
    index index.php index.html;
    server_name localhost;
    root /var/www/public;

    # Encaminha qualquer rota do Laravel para o index.php
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Despacha arquivos .php para o container PHP-FPM na porta 9000
    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # Bloqueia acesso a arquivos ocultos (como .env ou .git)
    location ~ /\.(?!well-known).* {
        deny all;
    }
}
