services:
  # 1. Serviço da Aplicação (FrankenPHP + Laravel)
  app:
    build:
      context: .
      dockerfile: dockerfile
    image: asclepio-app
    container_name: asclepio_app
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      SERVER_NAME: ":80"
      TZ: America/Sao_Paulo
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - asclepio-network

  # 2. Banco de Dados (MySQL 8.4)
  db:
    image: mysql:8.4
    container_name: asclepio_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: hospital_asclepio
      MYSQL_ROOT_PASSWORD: root
      TZ: America/Sao_Paulo
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - asclepio-network

networks:
  asclepio-network:
    driver: bridge

volumes:
  db_data:
