FROM dunglas/frankenphp:php8.5-alpine

# Instala pacotes do sistema
RUN apk add --no-cache \
    bash \
    curl \
    git \
    zip \
    unzip

# Instala as extensões PHP via script nativo do FrankenPHP
RUN install-php-extensions \
    pdo_mysql \
    mysqli \
    mbstring \
    exif \
    pcntl \
    bcmath \
    intl \
    gd \
    zip

# Instala o Composer diretamente da imagem oficial
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Diretório de trabalho dentro do container
WORKDIR /app

ENV SERVER_NAME=":80"

